// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu5Pt19_gWCxPX97Xk35lsjkXCI5sb684',
    appId: '1:653922675269:web:27fd1e91b3ad96cfe2d12c',
    messagingSenderId: '653922675269',
    projectId: 'bookzone-388c9',
    authDomain: 'bookzone-388c9.firebaseapp.com',
    storageBucket: 'bookzone-388c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7CSBQ3O5_OZ2aFo8QVu7ZBKN7kc65cpQ',
    appId: '1:653922675269:android:48f2c846532769c7e2d12c',
    messagingSenderId: '653922675269',
    projectId: 'bookzone-388c9',
    storageBucket: 'bookzone-388c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8K7uWmTgXF84h-5VnIwqhVi_MdUzupZQ',
    appId: '1:653922675269:ios:cfd839d693b82781e2d12c',
    messagingSenderId: '653922675269',
    projectId: 'bookzone-388c9',
    storageBucket: 'bookzone-388c9.appspot.com',
    iosClientId: '653922675269-vmlnkfd2espclruktmrvigeh75kd45cn.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8K7uWmTgXF84h-5VnIwqhVi_MdUzupZQ',
    appId: '1:653922675269:ios:cfd839d693b82781e2d12c',
    messagingSenderId: '653922675269',
    projectId: 'bookzone-388c9',
    storageBucket: 'bookzone-388c9.appspot.com',
    iosClientId: '653922675269-vmlnkfd2espclruktmrvigeh75kd45cn.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookstore',
  );
}
